#make a redis
version: "3.7"

services:
  cache-api:
    container_name: cache-api
    image: accusystechnology/cache-api:0.0.2
    restart: always
    ports:
      - 6000:6000
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: "redis://redis-stack-server"


